<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <PdnRoot Condition="'$(PdnRoot)' == ''">C:\Program Files\paint.net</PdnRoot>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <OutputPath>$(PdnRoot)\FileTypes\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ArbitraryPictureFormat.Core\ArbitraryPictureFormat.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PaintDotNet.Base">
      <HintPath>$(PdnRoot)\PaintDotNet.Base.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PaintDotNet.Collections">
      <HintPath>$(PdnRoot)\PaintDotNet.Collections.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PaintDotNet.ComponentModel">
      <HintPath>$(PdnRoot)\PaintDotNet.ComponentModel.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PaintDotNet.Core">
      <HintPath>$(PdnRoot)\PaintDotNet.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PaintDotNet.Data">
      <HintPath>$(PdnRoot)\PaintDotNet.Data.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PaintDotNet.Effects.Core">
      <HintPath>$(PdnRoot)\PaintDotNet.Effects.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PaintDotNet.Fundamentals">
      <HintPath>$(PdnRoot)\PaintDotNet.Fundamentals.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PaintDotNet.ObjectModel">
      <HintPath>$(PdnRoot)\PaintDotNet.ObjectModel.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PaintDotNet.Primitives">
      <HintPath>$(PdnRoot)\PaintDotNet.Primitives.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PaintDotNet.PropertySystem">
      <HintPath>$(PdnRoot)\PaintDotNet.PropertySystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PaintDotNet.Runtime">
      <HintPath>$(PdnRoot)\PaintDotNet.Runtime.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PaintDotNet.Windows.Core">
      <HintPath>$(PdnRoot)\PaintDotNet.Windows.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PaintDotNet.Windows">
      <HintPath>$(PdnRoot)\PaintDotNet.Windows.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Runtime.Serialization.Formatters">
      <HintPath>$(PdnRoot)\System.Runtime.Serialization.Formatters.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
